# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.0
jobs:
  build:
    docker:
      - image: circleci/node:11.10.1
    working_directory: ~/projectTwo
    steps:
      - checkout
      # Download and cache dependencies

      # - restore_cache:
      #     keys:
      #       - v1-dependencies-{{ checksum "my-app/package.json" }}
      #       # fallback to using the latest cache if no exact match is found
      #       - v1-dependencies-

      - run:
          name: Run Tests
          command: |
            echo "pretend testing"

      - run:
          name: Build Artifact
          command: |
            cd my-app
            npm install
            npm run build
            ls

      - persist_to_workspace:
          root: . # Persist current working directory
          paths: my-app/build/* # Glob. Will persist everything in folder

      
    
      # - save_cache:
      #     paths:
      #       - node_modules
      #     key: v1-dependencies-{{ checksum "my-app/package.json" }}



  pushToS3:
    docker:
      - image: 'circleci/python:2.7'
    working_directory: ~/projectTwo
    steps:
      - run: pwd
      - run: ls
      - attach_workspace:
          at: .
      - run: pwd
      - run: ls
      - run: |
          ls my-app
          cd my-app
          ls

      - run: ls
      - run: cd build
      - run: ls
      - aws-s3/sync:
          from: ~/projectTwo/my-app/build
          to: 's3://projecttworeact/'
          overwrite: true

# pushTos3:
#   docker:
#     - image: circleci/node:7.10
#   steps:



workflows:
  version: 2
  build_test_push:
    jobs:
      - build
      - pushToS3:
          requires:
            - build
          context: 'AWS'
